package autonewsroller;

import autonewsroller.config.*;import autonewsroller.orchestration.*;import java.nio.file.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;
public final class Main {
    public static void main(String[]args){Path root=Path.of("").toAbsolutePath().normalize();NewsConfig cfg=null;try{
        if(has(args,"--self-test")){new SelfTest().run(root);return;}cfg=NewsConfig.load(root);NewsConfig cleanupCfg=cfg;Runtime.getRuntime().addShutdownHook(new Thread(()->OwnedProcesses.shutdownQwen(root,cleanupCfg.get("qwenUrl","http://127.0.0.1:8765")),"autonewsroller-owned-helper-shutdown"));Map<String,String>o=parse(args);
        if(has(args,"--keep-ollama-loaded"))cfg.set("ollamaKeepAlive","30m");if(has(args,"--unload-ollama-after"))cfg.set("ollamaKeepAlive","0");boolean dry=has(args,"--dry-run");int target=intv(o,"--batch-target",dry?5:1);int workers=intv(o,"--workers",cfg.workers());String category=o.getOrDefault("--category","general");int maxAge=intv(o,"--max-age-hours",cfg.maxAgeHours());int min=intv(o,"--minimum-independent-sources",cfg.minimumIndependentSources());int duration=intv(o,"--duration",cfg.duration());String encoder=o.getOrDefault("--encoder",cfg.get("videoEncoder","auto"));boolean comfy=has(args,"--comfyui");String stamp=DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss").withZone(ZoneId.systemDefault()).format(Instant.now());Path batch=o.containsKey("--batch-dir")?root.resolve(o.get("--batch-dir")).normalize():root.resolve("output/batch_"+stamp);NewsPipeline p=new NewsPipeline(root,cfg,batch);BatchCoordinator.BatchResult r=new BatchCoordinator(root,p).run(target,workers,category,maxAge,min,duration,encoder,comfy,dry,has(args,"--fixture"),batch);System.out.println("Approved "+r.approved()+" / target "+target+" after "+r.attempts()+" attempt(s)");for(String e:r.errors())System.err.println("REJECTED "+e);if(r.approved()<target)System.exit(2);
    }catch(Exception e){e.printStackTrace();System.exit(1);}finally{if(cfg!=null)OwnedProcesses.shutdownQwen(root,cfg.get("qwenUrl","http://127.0.0.1:8765"));}}
    private static boolean has(String[]a,String k){for(String x:a)if(x.equalsIgnoreCase(k))return true;return false;}private static Map<String,String>parse(String[]a){Map<String,String>m=new HashMap<>();for(int i=0;i<a.length;i++)if(a[i].startsWith("--")&&i+1<a.length&&!a[i+1].startsWith("--"))m.put(a[i],a[++i]);return m;}private static int intv(Map<String,String>m,String k,int d){try{return Integer.parseInt(m.getOrDefault(k,String.valueOf(d)));}catch(Exception e){return d;}}
}
